CREATE DATABASE IF NOT EXISTS Merisier;


USE Merisier;


CREATE TABLE IF NOT EXISTS USERS (
    id BIGINT UNSIGNED PRIMARY KEY AUTOINCREMENTS,
    name VARCHAR(255),
    password VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS CATEGORIES (
    id BIGINT UNSIGNED PRIMARY KEY AUTOINCREMENTS,
    name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS PRODUCTS (
    id BIGINT UNSIGNED PRIMARY KEY AUTOINCREMENTS,
    name VARCHAR(255),
    quantity INT,
    status VARCHAR(50) CHECK (status IN ('disponnible', 'non disponnible')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    num_category BIGINT UNSIGNED,
    FOREIGN KEY (num_category) REFERENCES CATEGORIES(CATEGORIES.id)
);


CREATE TABLE IF NOT EXISTS TAGS (
    id BIGINT UNSIGNED PRIMARY KEY AUTOINCREMENTS,
    name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS ORDERS (
    id BIGINT UNSIGNED PRIMARY KEY AUTOINCREMENTS,
    num_invoice VARCHAR(100),
    status VARCHAR(50) CHECK (status IN ('En panier', 'En cours de traitement','Validé','En cours de livraison','Livré'))
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    num_user BIGINT UNSIGNED,
    FOREIGN KEY (num_user) REFERENCES USERS(USER.id)
);

CREATE TABLE IF NOT EXISTS PRODUCTS_ODERS (
    num_product BIGINT UNSIGNED,
    num_tag BIGINT UNSIGNED,
    PRIMARY KEY (num_product, num_tag),
    FOREIGN KEY (num_product) REFERENCES PRODUCTS(PRODUCTS.id),
    FOREIGN KEY (num_tag) REFERENCES TAGS(TAGS.id)
);

